CREATE TABLE person (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	username VARCHAR(100) NOT NULL,
	password TEXT NOT NULL,
	email VARCHAR(150) NOT NULL,
	dob DATE NOT NULL,
	created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE post (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	title VARCHAR(100) NOT NULL,
	content VARCHAR(350) NOT NULL,
	created_at TIMESTAMP DEFAULT now(),
	-- FOREIGN KEYS
	user_id INT NOT NULL REFERENCES person(id)
);

CREATE TABLE comment (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	content VARCHAR(350) NOT NULL,
	created_at TIMESTAMP DEFAULT now(),
	-- FOREIGN KEYS
	user_id INT NOT NULL REFERENCES person(id),
	post_id INT NOT NULL REFERENCES post(id)
);

CREATE TABLE saved (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	created_at TIMESTAMP DEFAULT now(),
	-- FOREIGN KEYS
	user_id INT NOT NULL REFERENCES person(id),
	post_id INT NOT NULL REFERENCES post(id)
);