CREATE TABLE user (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	username VARCHAR(100) NOT NULL,
	password TEXT NOT NULL,
	email VARCHAR(150) NOT NULL,
	dob DATE NOT NULL,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE post (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	title VARCHAR(100) NOT NULL,
	content VARCHAR(350) NOT NULL,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP
	-- FOREIGN KEYS
	FOREIGN KEY (uid) REFERENCES user(id),
);

CREATE TABLE comment (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	username VARCHAR(100) NOT NULL,
	password TEXT NOT NULL,
	email VARCHAR(150) NOT NULL,
	dob DATE NOT NULL,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE saved (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP
	-- FOREIGN KEYS
	FOREIGN KEY (uid) REFERENCES user(id),
	FOREIGN KEY (pid) REFERENCES post(id),
);